services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: dev
    container_name: siroko_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/99-custom.ini
    environment:
      - APP_ENV=dev
      - DATABASE_URL=postgresql://siroko:password@database:5432/siroko_cart?serverVersion=15&charset=utf8
      - REDIS_URL=redis://redis:6379
    depends_on:
      - database
      - redis
    networks:
      - siroko-network

  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    container_name: siroko_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - siroko-network

  database:
    image: postgres:15-alpine
    container_name: siroko_database
    restart: unless-stopped
    environment:
      POSTGRES_DB: siroko_cart
      POSTGRES_USER: siroko
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - siroko-network

  redis:
    image: redis:7-alpine
    container_name: siroko_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - siroko-network

networks:
  siroko-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
