# Infrastructure Services Configuration
services:
    # Repository Implementations
    App\Infrastructure\Persistence\Doctrine\Repository\DoctrineCartRepository:
        tags: ['doctrine.repository_service']

    App\Infrastructure\Persistence\Doctrine\Repository\DoctrineProductRepository:
        tags: ['doctrine.repository_service']

    App\Infrastructure\Persistence\Doctrine\Repository\DoctrineOrderRepository:
        tags: ['doctrine.repository_service']

    # Repository Interfaces Binding
    App\Domain\Repository\CartRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrineCartRepository

    App\Domain\Repository\ProductRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrineProductRepository

    App\Domain\Repository\OrderRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrineOrderRepository

    # Command and Query Handlers are auto-configured via #[AsMessageHandler] attributes
